use role accountadmin;

CREATE OR REPLACE WAREHOUSE TRI_DATA_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE TRI_DATA_ENGINE;

CREATE OR REPLACE SCHEMA TRI_DATA_ENGINE.RAW;

USE WAREHOUSE TRI_DATA_WH;
USE DATABASE TRI_DATA_ENGINE;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.STAGING_ORDERS_SF (
    OrderID INT,
    CustomerID INT,
    ItemName STRING,
    Quantity INT,
    Price DOUBLE,
    Date DATE,
    Status STRING
);

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '')
EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE TEMPORARY STAGE ORDERS_TEMP_STAGE
FILE_FORMAT = CSV_FORMAT;

SELECT COUNT(*) AS total_orders
FROM RAW.STAGING_ORDERS_SF;

SELECT 
    ROUND(SUM(Price * Quantity), 2) AS total_revenue,
    ROUND(AVG(Price * Quantity), 2) AS avg_order_value
FROM RAW.STAGING_ORDERS_SF;

-- Cleanup commands

-- DROP TABLE IF EXISTS RAW.STAGING_ORDERS_SF;
-- DROP FILE FORMAT IF EXISTS CSV_FORMAT;
-- DROP STAGE IF EXISTS ORDERS_TEMP_STAGE;
-- DROP DATABASE IF EXISTS TRI_DATA_ENGINE;
-- DROP WAREHOUSE IF EXISTS TRI_DATA_WH;